"""Persistence ports for journeys, objectives and decisions."""

from typing import Protocol

from domain.decision.models import DecisionContext, LearnerJourney, LearningDecision, PedagogicalObjective


class DecisionRepository(Protocol):
    def save_journey(self, journey: LearnerJourney) -> None: ...
    def load_journey(self, learner_id: int) -> LearnerJourney: ...
    def save_objective(self, learner_id: int, objective: PedagogicalObjective) -> None: ...
    def save_decision(self, context: DecisionContext, decision: LearningDecision) -> int: ...
    def get_decision_payload(self, correlation_id: str) -> dict | None: ...
