from __future__ import annotations
from subjects._helpers import generate_from_bank

SUBJECT_NAME = 'Géographie'
CHAPTERS = {'Urbanisation': {'summary': 'Comprendre la croissance des villes.', 'method': 'Étudier métropolisation, étalement et inégalités.', 'example': 'Une métropole concentre population et fonctions.', 'pitfalls': 'Ville et aire urbaine ne sont pas synonymes.', 'key_points': ['Métropole', 'Périurbanisation', 'Mégalopole']}, 'Mondialisation': {'summary': "Comprendre l'intensification des échanges.", 'method': 'Étudier flux, acteurs et territoires.', 'example': 'Les FTN organisent des chaînes de valeur.', 'pitfalls': 'La mondialisation est inégale.', 'key_points': ['Flux', 'FTN', 'Façade maritime']}, 'Mobilités humaines': {'summary': 'Étudier migrations et tourisme.', 'method': 'Identifier causes, routes et effets.', 'example': 'Migration économique ou forcée.', 'pitfalls': 'Ne pas confondre migrant et réfugié.', 'key_points': ['Migration', 'Réfugié', 'Tourisme']}, 'Espaces productifs': {'summary': 'Étudier agriculture, industrie et services.', 'method': 'Localiser et expliquer les dynamiques.', 'example': 'Technopôle et zone industrialo-portuaire.', 'pitfalls': 'Un espace productif peut être multifonctionnel.', 'key_points': ['Agriculture', 'Industrie', 'Services']}, 'Développement durable': {'summary': 'Articuler économie, société et environnement.', 'method': 'Comparer besoins présents et futurs.', 'example': 'Trois piliers du développement durable.', 'pitfalls': 'Le développement durable ne signifie pas absence de développement.', 'key_points': ['Économique', 'Social', 'Environnemental']}, 'Risques naturels': {'summary': 'Comprendre aléa, enjeu et vulnérabilité.', 'method': 'Évaluer prévention et adaptation.', 'example': 'Séisme + population exposée = risque.', 'pitfalls': "Un aléa sans enjeu n'est pas un risque majeur.", 'key_points': ['Aléa', 'Vulnérabilité', 'Prévention']}, 'France et territoires': {'summary': 'Comprendre organisation et dynamiques françaises.', 'method': 'Étudier métropoles, littoraux et espaces ruraux.', 'example': 'Paris domine le réseau urbain.', 'pitfalls': 'Ne pas oublier les territoires ultramarins.', 'key_points': ['Métropolisation', 'Littoraux', 'Outre-mer']}, 'Union européenne': {'summary': "Comprendre l'organisation et les contrastes de l'UE.", 'method': 'Étudier frontières, institutions et territoires.', 'example': 'Marché unique et espace Schengen.', 'pitfalls': 'UE, zone euro et Schengen ne coïncident pas exactement.', 'key_points': ['Institutions', 'Schengen', 'Zone euro']}, 'Inégalités mondiales': {'summary': 'Comparer niveaux de développement.', 'method': 'Utiliser IDH, richesse et accès aux services.', 'example': "L'IDH combine santé, éducation et revenu.", 'pitfalls': 'Le PIB seul ne mesure pas tout.', 'key_points': ['IDH', 'PIB', 'Développement']}}
BANK = {'Urbanisation': [("L'augmentation de la population vivant en ville s'appelle...", 'urbanisation', "C'est l'urbanisation.")], 'Mondialisation': [("L'intensification des échanges mondiaux s'appelle...", 'mondialisation', "C'est la mondialisation.")], 'Mobilités humaines': [('Un déplacement durable de population est une...', 'migration', "Il s'agit d'une migration.")], 'Espaces productifs': [("Quel secteur regroupe l'agriculture ?", 'primaire', "L'agriculture appartient au secteur primaire.")], 'Développement durable': [('Combien de piliers possède le développement durable ?', '3', 'Économique, social et environnemental.')], 'Risques naturels': [('Un séisme est-il un aléa naturel ?', 'oui', "Oui, c'est un aléa naturel.")], 'France et territoires': [('Quelle est la capitale de la France ?', 'paris', 'Paris est la capitale.')], 'Union européenne': [("Combien d'étoiles sur le drapeau européen ?", '12', 'Le drapeau compte 12 étoiles.')], 'Inégalités mondiales': [('Quel indicateur combine santé, éducation et niveau de vie ?', 'idh', "C'est l'IDH.", ['indice de développement humain'])]}

def generate_question(chapter: str, difficulty: str = "Moyen") -> dict:
    return generate_from_bank(chapter, BANK, difficulty)
