from __future__ import annotations
from subjects._helpers import generate_from_bank

SUBJECT_NAME = 'Espagnol'
CHAPTERS = {'Présent': {'summary': 'Conjuguer les verbes réguliers et fréquents.', 'method': 'Retirer -ar/-er/-ir et ajouter la terminaison.', 'example': 'Yo hablo.', 'pitfalls': 'Attention aux verbes à diphtongue.', 'key_points': ['-ar', '-er', '-ir']}, 'Pretérito perfecto': {'summary': "Parler d'un passé lié au présent.", 'method': 'Haber au présent + participe passé.', 'example': 'He comido.', 'pitfalls': 'Le participe reste invariable.', 'key_points': ['he/has/ha', '-ado/-ido']}, 'Pretérito indefinido': {'summary': 'Raconter une action passée terminée.', 'method': 'Utiliser les terminaisons du passé simple espagnol.', 'example': 'Él habló.', 'pitfalls': 'Apprendre les irréguliers fréquents.', 'key_points': ['hablé', 'comí', 'viví']}, 'Futur': {'summary': 'Exprimer un fait futur.', 'method': 'Infinitif + terminaisons du futur.', 'example': 'Viviremos.', 'pitfalls': 'Même terminaison pour les trois groupes.', 'key_points': ['é', 'ás', 'á', 'emos', 'éis', 'án']}, 'Ser et estar': {'summary': 'Distinguer identité/caractéristique et état/localisation.', 'method': 'Ser pour définir, estar pour situer ou état temporaire.', 'example': 'Madrid está en España.', 'pitfalls': 'Certaines expressions changent de sens.', 'key_points': ['Ser', 'Estar']}, 'Gustar': {'summary': 'Exprimer goûts et préférences.', 'method': 'Me/te/le + gusta(n).', 'example': 'Me gustan los libros.', 'pitfalls': 'Le sujet grammatical vient après le verbe.', 'key_points': ['gusta', 'gustan']}, 'Hay': {'summary': 'Exprimer « il y a ».', 'method': 'Utiliser hay, invariable.', 'example': 'Hay un parque.', 'pitfalls': 'Ne pas confondre hay et está.', 'key_points': ['Hay']}, 'Por et para': {'summary': 'Exprimer cause, moyen, destination ou but.', 'method': 'Por : cause/moyen ; para : but/destination.', 'example': 'Este regalo es para ti.', 'pitfalls': 'Apprendre les usages par exemples.', 'key_points': ['Por', 'Para']}, 'Vocabulaire': {'summary': 'Développer le lexique courant.', 'method': 'Apprendre par thèmes et réutiliser en phrase.', 'example': 'Casa = maison.', 'pitfalls': 'Attention aux faux amis.', 'key_points': ['Famille', 'École', 'Ville', 'Voyage']}, 'Compréhension': {'summary': 'Comprendre un texte simple.', 'method': 'Repérer cognats, mots clés et temps verbaux.', 'example': 'Siempre = toujours.', 'pitfalls': 'Ne pas traduire mot à mot.', 'key_points': ['Idée principale', 'Détails', 'Contexte']}}
BANK = {'Présent': [('Conjugue « hablar » avec yo.', 'hablo', 'Yo hablo.')], 'Pretérito perfecto': [('Complète : Hoy ___ comido. (yo)', 'he', 'He + participe passé.')], 'Pretérito indefinido': [('Conjugue « hablar » avec él au pretérito indefinido.', 'habló', 'Él habló.')], 'Futur': [('Conjugue « vivir » avec nosotros au futur.', 'viviremos', 'Infinitif + emos.')], 'Ser et estar': [('Complète : Madrid ___ en España.', 'está', 'La localisation se construit avec estar.')], 'Gustar': [('Complète : Me ___ los libros.', 'gustan', 'Los libros est pluriel.')], 'Hay': [('Traduis : Il y a un parc.', 'hay un parque', 'Hay signifie il y a.')], 'Por et para': [('Complète : Este regalo es ___ ti.', 'para', 'Para exprime la destination.')], 'Vocabulaire': [('Traduis « maison ».', 'casa', 'Maison = casa.')], 'Compréhension': [('Que signifie « siempre » ?', 'toujours', 'Siempre signifie toujours.')]}

def generate_question(chapter: str, difficulty: str = "Moyen") -> dict:
    return generate_from_bank(chapter, BANK, difficulty)
