from __future__ import annotations
from subjects._helpers import generate_from_bank

SUBJECT_NAME = 'Technologie'
CHAPTERS = {'Objets techniques': {'summary': "Analyser fonctions et contraintes d'un objet.", 'method': "Distinguer fonction d'usage et fonctions techniques.", 'example': 'Un vélo permet de se déplacer.', 'pitfalls': 'Ne pas confondre besoin et solution.', 'key_points': ['Besoin', "Fonction d'usage", 'Contrainte']}, "Chaîne d'énergie": {'summary': 'Identifier alimentation, distribution, conversion et transmission.', 'method': "Suivre le flux d'énergie.", 'example': 'Batterie → moteur → mouvement.', 'pitfalls': 'Chaque bloc a une fonction précise.', 'key_points': ['Alimenter', 'Distribuer', 'Convertir', 'Transmettre']}, "Chaîne d'information": {'summary': 'Identifier acquisition, traitement et communication.', 'method': "Suivre le flux d'information.", 'example': 'Capteur → programme → action.', 'pitfalls': 'Distinguer information et énergie.', 'key_points': ['Acquérir', 'Traiter', 'Communiquer']}, 'Programmation': {'summary': 'Comprendre variables, conditions et boucles.', 'method': "Lire l'algorithme étape par étape.", 'example': "Répéter jusqu'à une condition.", 'pitfalls': 'Attention aux boucles infinies.', 'key_points': ['Variable', 'Condition', 'Boucle']}, 'Réseaux': {'summary': 'Comprendre adressage et communication numérique.', 'method': 'Distinguer réseau local et Internet.', 'example': 'Une adresse IP identifie une interface.', 'pitfalls': 'Internet et Web ne sont pas synonymes.', 'key_points': ['IP', 'Routeur', 'Serveur', 'Protocole']}, 'Développement durable': {'summary': "Évaluer l'impact d'un objet sur son cycle de vie.", 'method': 'Étudier matériaux, énergie, réparation et recyclage.', 'example': 'Réparer prolonge la durée de vie.', 'pitfalls': "Recycler n'efface pas tous les impacts.", 'key_points': ['Cycle de vie', 'Éco-conception', 'Recyclage']}}
BANK = {'Objets techniques': [("La fonction principale rendue à l'utilisateur est la fonction...", "d'usage", "C'est la fonction d'usage.")], "Chaîne d'énergie": [("Quel bloc fournit l'énergie au système ?", 'alimenter', 'Le bloc alimenter.')], "Chaîne d'information": [('Quel bloc reçoit les informations des capteurs ?', 'acquérir', 'Le bloc acquérir.')], 'Programmation': [('Une instruction répétée plusieurs fois est une...', 'boucle', "C'est une boucle.")], 'Réseaux': [('Que signifie IP ?', 'internet protocol', 'IP signifie Internet Protocol.')], 'Développement durable': [("Réparer un objet favorise-t-il l'économie circulaire ?", 'oui', 'Oui, cela prolonge sa durée de vie.')]}

def generate_question(chapter: str, difficulty: str = "Moyen") -> dict:
    return generate_from_bank(chapter, BANK, difficulty)
